// components/refactors-panel.tsx
"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Wrench,
  Clock,
  Zap,
  ChevronDown,
  Copy,
  Check,
  TrendingUp,
  ExternalLink,
  FileCode,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { Refactor } from "@/lib/types";
import { cn } from "@/lib/utils";
import Link from "next/link";

interface RefactorsPanelProps {
  refactors: Refactor[];
  repoFullName?: string;
}

const impactConfig = {
  high: {
    color: "bg-red-500/10 text-red-500 border-red-500/20",
    label: "High Impact",
    shortLabel: "High",
  },
  medium: {
    color: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
    label: "Medium Impact",
    shortLabel: "Medium",
  },
  low: {
    color: "bg-green-500/10 text-green-500 border-green-500/20",
    label: "Low Impact",
    shortLabel: "Low",
  },
};

const effortConfig = {
  high: {
    icon: Clock,
    color: "text-red-500",
    label: "High Effort",
    shortLabel: "High",
  },
  medium: {
    icon: Clock,
    color: "text-yellow-500",
    label: "Medium Effort",
    shortLabel: "Medium",
  },
  low: {
    icon: Zap,
    color: "text-green-500",
    label: "Quick Win",
    shortLabel: "Quick",
  },
};

function isValidRefactor(refactor: Refactor): boolean {
  // Filter out empty or invalid refactors
  if (!refactor) return false;
  if (!refactor.title || refactor.title.trim() === "") return false;
  if (!refactor.description || refactor.description.trim() === "") return false;
  if (!refactor.impact || !["high", "medium", "low"].includes(refactor.impact))
    return false;
  if (!refactor.effort || !["high", "medium", "low"].includes(refactor.effort))
    return false;
  return true;
}

function RefactorItem({
  refactor,
  index,
  repoFullName,
}: {
  refactor: Refactor;
  index: number;
  repoFullName?: string;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const EffortIcon = effortConfig[refactor.effort]?.icon || Clock;
  const isQuickWin =
    refactor.effort === "low" &&
    (refactor.impact === "high" || refactor.impact === "medium");

  const hasCode =
    refactor.suggestedCode && refactor.suggestedCode.trim() !== "";

  const handleCopy = async (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (hasCode) {
      await navigator.clipboard.writeText(refactor.suggestedCode!);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const getGitHubIssueUrl = () => {
    if (!repoFullName) return null;

    const filesSection =
      refactor.files && refactor.files.length > 0
        ? `### Affected Files\n${refactor.files.map((f) => `- \`${f}\``).join("\n")}`
        : "";

    const codeSection = hasCode
      ? `### Suggested Implementation\n\`\`\`\n${refactor.suggestedCode}\n\`\`\``
      : "";

    const body = `## Refactoring Suggestion: ${refactor.title}

### Description
${refactor.description}

### Details
| Attribute | Value |
|-----------|-------|
| **Impact** | ${refactor.impact} |
| **Effort** | ${refactor.effort} |
| **Category** | ${refactor.category || "General"} |

${filesSection}

${codeSection}

---
*Generated by CodeSight*`;

    const params = new URLSearchParams({
      title: `[Refactor] ${refactor.title}`,
      body: body,
      labels: "refactoring,enhancement",
    });

    return `https://github.com/${repoFullName}/issues/new?${params}`;
  };

  const githubIssueUrl = getGitHubIssueUrl();

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
    >
      <div
        className={cn(
          "rounded-xl border bg-background transition-all duration-200 overflow-hidden",
          isOpen && "border-primary/30 shadow-sm",
          isQuickWin && !isOpen && "border-green-500/20",
        )}
      >
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="w-full p-3 sm:p-4 text-left hover:bg-accent/30 transition-colors"
        >
          <div className="flex items-start gap-2 sm:gap-3">
            <div
              className={cn(
                "p-1.5 sm:p-2 rounded-lg shrink-0",
                isQuickWin ? "bg-green-500/10" : "bg-primary/10",
              )}
            >
              {isQuickWin ? (
                <Zap className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-green-500" />
              ) : (
                <Wrench className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary" />
              )}
            </div>

            <div className="flex-1 min-w-0">
              <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2 mb-1">
                <div className="flex items-center gap-2 flex-wrap">
                  {isQuickWin && (
                    <Badge className="bg-green-500/10 text-green-600 border-green-500/20 text-[10px] h-5 px-1.5">
                      <Zap className="w-2.5 h-2.5 mr-0.5" />
                      Quick Win
                    </Badge>
                  )}
                  <Badge
                    variant="outline"
                    className={cn(
                      "text-[10px] h-5 px-1.5 shrink-0",
                      impactConfig[refactor.impact]?.color,
                    )}
                  >
                    <TrendingUp className="w-2.5 h-2.5 mr-0.5" />
                    <span className="hidden sm:inline">
                      {impactConfig[refactor.impact]?.label}
                    </span>
                    <span className="sm:hidden">
                      {impactConfig[refactor.impact]?.shortLabel}
                    </span>
                  </Badge>
                </div>
              </div>

              <h4 className="font-medium text-sm mt-1.5 line-clamp-2 sm:line-clamp-1 pr-4">
                {refactor.title}
              </h4>

              <p className="text-xs sm:text-sm text-muted-foreground line-clamp-2 mt-1">
                {refactor.description}
              </p>

              <div className="flex items-center gap-2 sm:gap-3 mt-2 flex-wrap">
                <div className="flex items-center gap-1 sm:gap-1.5">
                  <EffortIcon
                    className={cn(
                      "w-3 h-3 sm:w-3.5 sm:h-3.5",
                      effortConfig[refactor.effort]?.color,
                    )}
                  />
                  <span className="text-[10px] sm:text-xs text-muted-foreground">
                    <span className="hidden sm:inline">
                      {effortConfig[refactor.effort]?.label}
                    </span>
                    <span className="sm:hidden">
                      {effortConfig[refactor.effort]?.shortLabel}
                    </span>
                  </span>
                </div>
                {refactor.category && (
                  <Badge
                    variant="secondary"
                    className="text-[10px] sm:text-xs h-5"
                  >
                    {refactor.category}
                  </Badge>
                )}
                {refactor.files && refactor.files.length > 0 && (
                  <div className="flex items-center gap-1 text-muted-foreground">
                    <FileCode className="w-3 h-3" />
                    <span className="text-[10px] sm:text-xs">
                      {refactor.files.length} file
                      {refactor.files.length !== 1 ? "s" : ""}
                    </span>
                  </div>
                )}
              </div>
            </div>

            <motion.div
              animate={{ rotate: isOpen ? 180 : 0 }}
              transition={{ duration: 0.2 }}
              className="shrink-0"
            >
              <ChevronDown className="w-4 h-4 sm:w-5 sm:h-5 text-muted-foreground" />
            </motion.div>
          </div>
        </button>

        <AnimatePresence>
          {isOpen && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.2 }}
            >
              <div className="px-3 sm:px-4 pb-3 sm:pb-4 space-y-3 sm:space-y-4 border-t pt-3 sm:pt-4">
                {/* Affected Files */}
                {refactor.files && refactor.files.length > 0 && (
                  <div>
                    <h5 className="text-[10px] sm:text-xs font-medium text-muted-foreground mb-2">
                      Affected Files
                    </h5>
                    <div className="flex flex-wrap gap-1.5">
                      {refactor.files.map((file) => (
                        <code
                          key={file}
                          className="text-[10px] sm:text-xs bg-muted px-2 py-1 rounded-md font-mono"
                        >
                          {file}
                        </code>
                      ))}
                    </div>
                  </div>
                )}

                {/* Suggested Code */}
                {hasCode && (
                  <div>
                    <h5 className="text-[10px] sm:text-xs font-medium text-muted-foreground mb-2">
                      Suggested Implementation
                    </h5>
                    <div className="relative rounded-lg bg-muted/50 border overflow-hidden">
                      <ScrollArea className="h-45 sm:h-55">
                        <pre className="p-3 text-[10px] sm:text-xs font-mono whitespace-pre-wrap wrap-break-word leading-relaxed">
                          {refactor.suggestedCode}
                        </pre>
                      </ScrollArea>
                    </div>
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row gap-2 pt-1">
                  {hasCode && (
                    <Button
                      variant="outline"
                      size="sm"
                      className="text-xs"
                      onClick={() => handleCopy()}
                    >
                      {copied ? (
                        <>
                          <Check className="w-3.5 h-3.5 mr-1.5 text-green-500" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5 mr-1.5" />
                          Copy Code
                        </>
                      )}
                    </Button>
                  )}

                  {githubIssueUrl && (
                    <Button size="sm" asChild className="text-xs">
                      <Link
                        href={githubIssueUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <ExternalLink className="w-3.5 h-3.5 mr-1.5" />
                        Create Issue on GitHub
                      </Link>
                    </Button>
                  )}

                  {repoFullName &&
                    refactor.files &&
                    refactor.files.length > 0 && (
                      <Button
                        variant="secondary"
                        size="sm"
                        asChild
                        className="text-xs"
                      >
                        <Link
                          href={`https://github.com/${repoFullName}/blob/main/${refactor.files[0]}`}
                          target="_blank"
                          rel="noopener noreferrer"
                        >
                          <FileCode className="w-3.5 h-3.5 mr-1.5" />
                          View File
                        </Link>
                      </Button>
                    )}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export function RefactorsPanel({
  refactors = [],
  repoFullName,
}: RefactorsPanelProps) {
  const safeRefactors = Array.isArray(refactors) ? refactors : [];

  // Filter out invalid refactors
  const validRefactors = safeRefactors.filter(isValidRefactor);

  // Sort by impact (high first) then by effort (low first for quick wins)
  const sortedRefactors = [...validRefactors].sort((a, b) => {
    const impactOrder = { high: 0, medium: 1, low: 2 };
    const effortOrder = { low: 0, medium: 1, high: 2 };
    const impactDiff =
      (impactOrder[a.impact] || 1) - (impactOrder[b.impact] || 1);
    if (impactDiff !== 0) return impactDiff;
    return (effortOrder[a.effort] || 1) - (effortOrder[b.effort] || 1);
  });

  const quickWins = sortedRefactors.filter(
    (r) => r.effort === "low" && (r.impact === "high" || r.impact === "medium"),
  );

  const highImpactCount = sortedRefactors.filter(
    (r) => r.impact === "high",
  ).length;

  return (
    <Card className="h-full flex flex-col bg-background">
      <CardHeader className="p-3 sm:pb-3 sm:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <CardTitle className="flex items-center gap-2 text-base sm:text-lg">
            <Wrench className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
            <div className="flex lg:flex-row flex-col gap-1">
              <span className="truncate">Refactoring Suggestions</span>
              {highImpactCount > 0 && (
                <Badge
                  variant="outline"
                  className="text-[10px] h-5 ml-1 bg-red-500/10 text-red-500 border-red-500/20"
                >
                  {highImpactCount} High Impact
                </Badge>
              )}
            </div>
          </CardTitle>
          <div className="flex gap-1.5 sm:gap-2">
            <Badge variant="secondary" className="text-[10px] sm:text-xs h-5">
              {sortedRefactors.length} suggestion
              {sortedRefactors.length !== 1 ? "s" : ""}
            </Badge>
            {quickWins.length > 0 && (
              <Badge className="bg-green-500/10 text-green-600 border-green-500/20 text-[10px] sm:text-xs h-5">
                <Zap className="w-2.5 h-2.5 sm:w-3 sm:h-3 mr-1" />
                {quickWins.length} Quick Win{quickWins.length !== 1 ? "s" : ""}
              </Badge>
            )}
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex-1 min-h-0 p-0">
        <ScrollArea className="h-full px-3 sm:px-6 pb-4">
          <div className="space-y-2 sm:space-y-3">
            {sortedRefactors.map((refactor, index) => (
              <RefactorItem
                key={refactor.id || index}
                refactor={refactor}
                index={index}
                repoFullName={repoFullName}
              />
            ))}

            {sortedRefactors.length === 0 && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex flex-col items-center justify-center py-16 text-muted-foreground"
              >
                <div className="w-12 h-12 rounded-full bg-muted/50 flex items-center justify-center mb-4">
                  <Wrench className="w-6 h-6 opacity-40" />
                </div>
                <p className="font-medium text-sm sm:text-base">
                  No refactoring suggestions
                </p>
                <p className="text-xs sm:text-sm mt-1 text-center max-w-62.5">
                  The codebase looks well-structured!
                </p>
              </motion.div>
            )}
          </div>
          <ScrollBar orientation="vertical" />
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
